dist: xenial
language: python
python:
  - 3.7

before_install:
  - pip install poetry

install:
  - poetry install

jobs:
  include:
    - stage: Python tests
      script: poetry run black --check .
    - stage: Python tests
      script: poetry run flake8 .
    - stage: Python tests
      script: mypy --ignore-missing-imports .
